[package]
name = "popstar_rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "popstar_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
rand = "0.9"
rayon = "1.10"
